spring.application.name=ai
# alias for the Gemini API key
#spring.ai.google.generativeai.chat.options.model=gemini-1.5-flash-latest

spring.ai.google.generativeai.api-key=AIzaSyBI9xscLxG4znwfht3NCU1dRqD0AV_Av6E
spring.ai.google.generativeai.chat.options.model=gemini-1.5-flash-latest